# Generated by Django 5.2.1 on 2025-05-12 19:48

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = []

    operations = [
        migrations.CreateModel(
            name="Author",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("name", models.CharField(max_length=200)),
                ("email", models.EmailField(max_length=254, unique=True)),
                ("affeliation", models.CharField(max_length=200)),
                ("orcId", models.CharField(max_length=200)),
            ],
        ),
        migrations.CreateModel(
            name="Publication",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("title", models.CharField(max_length=200)),
                ("abstract", models.TextField()),
                ("pub_date", models.DateTimeField(verbose_name="date published")),
                ("summary", models.TextField()),
                (
                    "authors",
                    models.ManyToManyField(
                        related_name="publications", to="publications.author"
                    ),
                ),
            ],
        ),
    ]
